### ISSUE TITLE
无法连接

### ISSUE THREAD

**Issue by EricaNoir** [Bluefissure/Dalamud-OBS#10]
用了ws://locahost:port和密码，网页可以连接上但游戏内插件连不上，不知道为什么

**Comment by EricaNoir** [comment]
找到了act的版本，试了一下127.0.0.1:port，act和卫月的还是都连不上…

**Comment by Bluefissure** [comment]
检查下防火墙等等，或者尝试其他obswebsockets的程序检查能否正常连接。

**Comment by EricaNoir** [comment]
其他的网页以及Touch Portal都可以正常连接

**Comment by Bluefissure** [comment]
> 其他的网页以及Touch Portal都可以正常连接

有使用加速器吗

**Comment by EricaNoir** [comment]
没，我在墙外裸连的> > 其他的网页以及Touch Portal都可以正常连接
> 
> 
> 
> 有使用加速器吗

**Comment by Bluefissure** [comment]
> 没，我在墙外裸连的> > 其他的网页以及Touch Portal都可以正常连接
> 
> > 有使用加速器吗

你使用的 obs 是什么版本？
所使用的 obs-websocket 插件是什么版本？
