### ISSUE TITLE
Alternative to StreamFX

### ISSUE THREAD

**Issue by GyroMachinist** [Bluefissure/Dalamud-OBS#15]
Hi, since StreamFX has went behind a paywall, is there any alternatives this plugin could consider with OBS

Some of us can't simply fork over $10/month for Patreon.

**Comment by Bluefissure** [comment]
https://github.com/prgmitchell/blur-filter
I may update the links in Plugin later.

**Comment by Bluefissure** [comment]
Starting from 1.0.2.5, we switch to [obs-composite-blur](https://github.com/FiniteSingularity/obs-composite-blur).
