### ISSUE TITLE
7.0 Update

### ISSUE THREAD

**Issue by Rider43** [Bluefissure/Dalamud-OBS#23]
Is there any plan to bring this up to date with 7.0?

**Comment by Bluefissure** [comment]
I made the PR https://github.com/goatcorp/DalamudPluginsD17/pull/3851
but goatcorp may be stuggling with some tech issues rn https://github.com/goatcorp/DalamudPluginsD17/issues/3848

**Comment by Rider43** [comment]
Thanks for updating it. Hopefully when goats get it resolved.

**Comment by Bluefissure** [comment]
You can use the temporary build at https://github.com/Bluefissure/Dalamud-OBS/releases/tag/1.0.4.0 for now

**Comment by Bluefissure** [comment]
It should be updated now
