### ISSUE TITLE
Bugs related to start of recording

### ISSUE THREAD

**Issue by 4i7** [Bluefissure/Dalamud-OBS#3]
The "Start Recording on CountDown" checkbox is not functioning, so recording starts on its own at the start of the count regardless of whether it is checked or not.
![image](https://user-images.githubusercontent.com/3959289/160301164-1e54143c-9c92-4e15-86b9-ecc0c9f5b564.png)

**Comment by Bluefissure** [comment]
Yes, start on countdown means start when countdown starts, not countdown ends.

If you want start on countdown ends, a better way should be starts when in combat?

**Comment by 4i7** [comment]
I want to stop PT members from being recorded automatically when they use the countdown function.

**Comment by Bluefissure** [comment]
I created the config but didn't actually use it somehow, I'm dumb.
Should be good after v1.0.1.1.
