### ISSUE TITLE
Party List blur appears to target the wrong HUD element

### ISSUE THREAD

**Issue by Kliuqard** [Bluefissure/Dalamud-OBS#31]
![image](https://github.com/user-attachments/assets/972bb81d-7e7b-443d-bbc0-065a78c8418b)

When PartyList blur is enabled, it wishes to target the PartyList number rather than the name. Or, I at least assume it is intended to blur the name.

**Comment by Bluefissure** [comment]
Fixed after https://github.com/goatcorp/DalamudPluginsD17/pull/5266#event-15742771460
