### ISSUE TITLE
chat blur will have several filter and be overlap

### ISSUE THREAD

**Issue by lee89tw14** [Bluefissure/Dalamud-OBS#6]
I'm using the blur function, but it seems that the chatpanel 1, 2 and 3 not going the setting with chatpanel
![image](https://user-images.githubusercontent.com/22855239/170851869-33e080d1-f255-45ad-9278-4da568a25fe1.png)
when I turn off or changing the chatpanel size they still be there the size before I resize it

![image](https://user-images.githubusercontent.com/22855239/170851939-6ba73a0c-961a-4baa-8f4a-893e68fab7dc.png)
chatpanel_0 and chatpanel work fine but not 1, 2 ,3

edit:
sorry, chatpanel_0 also not work fine, onlt the filter named chatpanel will goes with ws setting in FFXIV

**Comment by Bluefissure** [comment]
I think the chatpanel_1/2/3 doesn't have a disposal function for its blur, May fix this in next release.

**Comment by Bluefissure** [comment]
Should be fixed in https://github.com/goatcorp/DalamudPluginsD17/pull/301, sorry it takes so long.
